Fix potentially failing test
Summary:
`test_robust` occasionally finds more inliers (see output below).
This happens because `random` can also be very close to zero. This diff fixes this problem by adding a `0.01` offset

Output:

```
    def test_outliers_line_ransac() -> None:
        a, b, x, samples = line_data()

        scale = 2.0
        y = a * x + b + np.random.rand(x.shape[0]) * scale

        ratio_outliers = 0.4
        outliers_max = 5.0
        add_outliers(ratio_outliers, x, scale, outliers_max)

        data = np.array([x, y]).transpose()

        params = pyrobust.RobustEstimatorParams()
        result = pyrobust.ransac_line(data, scale, params, pyrobust.RansacType.RANSAC)

        inliers_count = (1 - ratio_outliers) * samples
>       assert result.score == inliers_count
E       assert 61.0 == 60.0
E        +  where 61.0 = <opensfm.pyrobust.ScoreInfoLine object at 0x7fb31b810fb0>.score
```

Reviewed By: YanNoun

Differential Revision: D34211202

fbshipit-source-id: c903f6bc33e1f298234604aa444b05a6b0be0e51